services:
  - type: web
    name: novda-worker-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: WORKER_BOT_TOKEN
        sync: false
      - key: WORKER_AUTH_HMAC_SECRET
        sync: false
      - key: WORKER_WEBAPP_URL
        value: "https://sync.novdatextile.uz/worker-app"
      - key: DEFAULT_COMPANY_ID
        value: "comp_novda"
      - key: PORT
        value: "10000"
      - key: FIREBASE_DATABASE_URL
        value: "https://hisobchi-c930c-default-rtdb.asia-southeast1.firebasedatabase.app"
